### ISSUE TITLE
Uptime Specs

### ISSUE THREAD

**Issue by b4iknew** [piotrpdev/Windows-screenFetch-fast#3]
Sorry I had no idea where to post about this. After having screenfetch displayed in a sinigle console for a few hours or even minutes, if I reissue the command screenfetch the "Uptime" is not updated. It does update my virtual drives but not the Uptime.
Is there something I could do to have the "Uptime" update?
Thanks in advance!

**Comment by piotrpdev** [comment]
Sorry, but I believe this issue is common and could occur for a multitude of reasons[[1]](https://social.technet.microsoft.com/Forums/en-US/b2cb5a29-8317-4c1a-a555-99ac79bebe7c/windows-10-lastbootuptime-not-updating?forum=win10itprogeneral)[[2]](https://stackoverflow.com/questions/31400544/wmi-lastbootuptime-is-not-updated-when-server-reboots).

It could also be occurring because of a bug in the code, but I wouldn't even know where to begin looking for it.

**Comment by AkariiinMKII** [comment]
Because `Get-CimInstance Win32_OperatingSystem` is run and cached in advance, it won't positively update until being placed in function field

**Comment by piotrpdev** [comment]
Please update to @AkariiinMKII's screenFetch instead of this one: https://github.com/AkariiinMKII/Windows-screenFetch
